spring:
    application:
        name: jChat-user
    rabbitmq:
        port: 5672
        host: 192.168.1.103
        virtual-host: /
        username: admin
        password: admin
    cloud:
        nacos:
            config:
                file-extension: yml
                server-addr: 127.0.0.1:8848
                username: nacos
                password: nacos
    data:
        redis:
            host: 192.168.1.103
    config:
        import:
           - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
fdfs:
    so-timeout: 2000
    connect-timeout: 2000
    thumb-image:
        width: 100
        height: 100
    tracker-list:
        - 192.168.1.103:22122
fastpath: http://192.168.1.103:8888/